%%% script written by: Sam Murphy 
%%%% purpose: read in the csv with the fractions of vegetation covering my
%%%% vprm domain and make bar charts to compare across years 

clear all

% set the path to the data 
path_data = '/storage/group/zrb5027/default/INFLUX/smm8236/vprm_gridded_analysis/PFT_yearly_fractions.csv'; 

% load in as a table to see the column headers 
PFT_frac_table = readtable(path_data); 

% read in the years 
years(:,1) = PFT_frac_table{:,'year'}; 

% read in all the PFTs (including no data)
no_data = PFT_frac_table{:,'no_data'}; 
corn = PFT_frac_table{:,'corn'}; 
other_crops = PFT_frac_table{:,'other_crops'}; 
urban = PFT_frac_table{:,'urban'}; 
wetlands = PFT_frac_table{:,'wetlands'}; 
Herbaceuous_Grassland_Hay_Pasture = PFT_frac_table{:,'Herbaceuous_Grassland_Hay_Pasture'}; 
dbf = PFT_frac_table{:,'dbf'}; 
Evergreen_North = PFT_frac_table{:,'Evergreen_North'}; 
Shrub_Scrub = PFT_frac_table{:,'Shrub_Scrub'}; 
Evergreen_South = PFT_frac_table{:,'Evergreen_South'}; 

% okay now let's make a bar chart where year is color coded 
bar_group_PFTs = [no_data(1) no_data(2) no_data(3) no_data(4) no_data(5) no_data(6) ...
    no_data(7) no_data(8) no_data(9) no_data(10); corn(1) corn(2) corn(3) corn(4) corn(5) ...
    corn(6) corn(7) corn(8) corn(9) corn(10); other_crops(1) other_crops(2) other_crops(3) ... 
    other_crops(4) other_crops(5) other_crops(6) other_crops(7) other_crops(8) other_crops(9) other_crops(10) ...
    ; urban(1) urban(2) urban(3) urban(4) urban(5) urban(6) urban(7) urban(8) urban(9) urban(10)...
    ; wetlands(1) wetlands(2) wetlands(3) wetlands(4) wetlands(5) wetlands(6) wetlands(7)...
    wetlands(8) wetlands(9) wetlands(10); ...
    Herbaceuous_Grassland_Hay_Pasture(1) Herbaceuous_Grassland_Hay_Pasture(2)...
    Herbaceuous_Grassland_Hay_Pasture(3) Herbaceuous_Grassland_Hay_Pasture(4) ...
    Herbaceuous_Grassland_Hay_Pasture(5) Herbaceuous_Grassland_Hay_Pasture(6) ...
    Herbaceuous_Grassland_Hay_Pasture(7) Herbaceuous_Grassland_Hay_Pasture(8)... 
    Herbaceuous_Grassland_Hay_Pasture(9) Herbaceuous_Grassland_Hay_Pasture(10)...
    ; dbf(1) dbf(2) dbf(3) dbf(4) dbf(5) ...
    dbf(6) dbf(7) dbf(8) dbf(9) dbf(10); Evergreen_North(1) Evergreen_North(2) ...
    Evergreen_North(3) Evergreen_North(4) Evergreen_North(5) Evergreen_North(6) ...
    Evergreen_North(7) Evergreen_North(8) Evergreen_North(9)  Evergreen_North(10); Shrub_Scrub(1) ...
    Shrub_Scrub(2) Shrub_Scrub(3) Shrub_Scrub(4) Shrub_Scrub(5) Shrub_Scrub(6)...
    Shrub_Scrub(7) Shrub_Scrub(8) Shrub_Scrub(9) Shrub_Scrub(10); Evergreen_South(1) ...
    Evergreen_South(2) Evergreen_South(3) Evergreen_South(4) Evergreen_South(5) ...
    Evergreen_South(6) Evergreen_South(7) Evergreen_South(8) Evergreen_South(9) Evergreen_South(10)]; 

figure()
b = bar(bar_group_PFTs); 
grid on 
% b(1).FaceColor = 
%xticklabels({'Model Total','Model Corn','Model Other Crops','Model DBF'})
%ylabel('Average July 2018 Afternoon Biogenic CO_2 [ppm]','FontSize',12)


% okay now let's make a plot for just 2017,2018,2019 
bar_group_PFTs_subset = [no_data(6) ...
    no_data(7) no_data(8) ;  ...
    corn(6) corn(7) corn(8) ;  ... 
     other_crops(6) other_crops(7) other_crops(8) ...
    ;  urban(6) urban(7) urban(8) ...
    ; wetlands(6) wetlands(7)...
    wetlands(8) ; ...
    Herbaceuous_Grassland_Hay_Pasture(6) ...
    Herbaceuous_Grassland_Hay_Pasture(7) Herbaceuous_Grassland_Hay_Pasture(8)... 
    ;  ...
    dbf(6) dbf(7) dbf(8) ;  ...
    Evergreen_North(6) ...
    Evergreen_North(7) Evergreen_North(8) ;  ...
    Shrub_Scrub(6)...
    Shrub_Scrub(7) Shrub_Scrub(8) ;  ...
      ...
    Evergreen_South(6) Evergreen_South(7) Evergreen_South(8) ]; 


figure()
b = bar(bar_group_PFTs_subset*100); 
grid on 
% b(1).FaceColor = 
legend({'2017','2018','2019'})
xticklabels({'No Data','Corn','Other Crops','Urban','Wetlands',...
    'Grasslands', 'DBF', 'Evergreen (North)', ... 
    'Shrub & Scrub', 'Evergreen (South)'})
ylabel('Percent of Domain','FontSize',12)



% okay now let's make a plot for just 2017,2018,2019,2020
bar_group_PFTs_subset_2 = [no_data(6) no_data(7) no_data(8) no_data(9) ;  ...
    corn(6) corn(7) corn(8) corn(9) ;  ... 
    other_crops(6) other_crops(7) other_crops(8) other_crops(9) ; ...
    urban(6) urban(7) urban(8) urban(9) ; ...
    wetlands(6) wetlands(7) wetlands(8) wetlands(9); ...
    Herbaceuous_Grassland_Hay_Pasture(6) Herbaceuous_Grassland_Hay_Pasture(7) ...
    Herbaceuous_Grassland_Hay_Pasture(8) Herbaceuous_Grassland_Hay_Pasture(9);  ...
    dbf(6) dbf(7) dbf(8) dbf(9);  ...
    Evergreen_North(6) Evergreen_North(7) Evergreen_North(8) Evergreen_North(9);  ...
    Shrub_Scrub(6) Shrub_Scrub(7) Shrub_Scrub(8) Shrub_Scrub(9);  ...
    Evergreen_South(6) Evergreen_South(7) Evergreen_South(8) Evergreen_South(9)]; 


figure()
b = bar(bar_group_PFTs_subset_2*100); 
grid on 
b(1).FaceColor = '#f6d777'; 
b(2).FaceColor = '#db5238'; 
b(3).FaceColor = '#79a874'; 
b(4).FaceColor = '#583f8e'; 
h=gca; 
h.XAxis.TickLength = [0 0]; 
h.YAxis.TickLength = [0 0]; 
legend({'2017','2018','2019','2020'})
xticklabels({'No Data & Water','Corn','Other Crops','Urban','Wetlands',...
    'Grasslands', 'DBF', 'Evergreen (North)', ... 
    'Shrub & Scrub', 'Evergreen (South)'})
ylabel('Percent of Domain')%,'FontSize',12)



% okay now let's make a plot for just 2017,2018,2019,2020, and 2021
bar_group_PFTs_subset_3 = [no_data(6) no_data(7) no_data(8) no_data(9) no_data(10) ;  ...
    corn(6) corn(7) corn(8) corn(9) corn(10) ;  ... 
    other_crops(6) other_crops(7) other_crops(8) other_crops(9) other_crops(10) ; ...
    urban(6) urban(7) urban(8) urban(9) urban(10) ; ...
    wetlands(6) wetlands(7) wetlands(8) wetlands(9) wetlands(10); ...
    Herbaceuous_Grassland_Hay_Pasture(6) Herbaceuous_Grassland_Hay_Pasture(7) ...
    Herbaceuous_Grassland_Hay_Pasture(8) Herbaceuous_Grassland_Hay_Pasture(9) Herbaceuous_Grassland_Hay_Pasture(10);  ...
    dbf(6) dbf(7) dbf(8) dbf(9) dbf(10);  ...
    Evergreen_North(6) Evergreen_North(7) Evergreen_North(8) Evergreen_North(9) Evergreen_North(10);  ...
    Shrub_Scrub(6) Shrub_Scrub(7) Shrub_Scrub(8) Shrub_Scrub(9) Shrub_Scrub(10);  ...
    Evergreen_South(6) Evergreen_South(7) Evergreen_South(8) Evergreen_South(9) Evergreen_South(10)]; 


figure()
b = bar(bar_group_PFTs_subset_3*100); 
grid on 
b(1).FaceColor = '#f6d777'; 
b(2).FaceColor = '#db5238'; 
b(3).FaceColor = '#79a874'; 
b(4).FaceColor = '#583f8e'; 
b(5).FaceColor = '#eea9ec'; 
h=gca; 
h.XAxis.TickLength = [0 0]; 
h.YAxis.TickLength = [0 0]; 
legend({'2017','2018','2019','2020','2021'})
xticklabels({'No Data & Water','Corn','Other Crops','Urban','Wetlands',...
    'Grasslands', 'DBF', 'Evergreen (North)', ... 
    'Shrub & Scrub', 'Evergreen (South)'})
ylabel('Percent of Domain')%,'FontSize',12)

